# Generated by Django 4.1.7 on 2023-02-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auction_id_alter_bid_id_alter_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='isAvailable',
            new_name='is_available',
        ),
    ]
